### ISSUE TITLE
ジャスパー用装備・楽器類・アセットの取り扱いについて

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#12]
ジャスパー用装備と楽器類について、現在レシピ上に作成レシピの登録がありますが、アイテム項目が全くない状況となっています。また、アセット類についても同様です。
それらのアイテムについては、現状のアイテム項目のレイアウトでは格納できないデータを保持しているため、それらを登録するためには専用のレイアウトを用意する必要があるかと思います。

とりあえず私のほうで先走って作ってしまったもの（お恥ずかしい…）はあるのですが、これではおそらく専用項目についての管理などが出来ず、データベースとしてのこのプロジェクトの方針と反するかなと思い、issueとして提出させていただきます。

一応私のほうで作成したデータのリンクを送付いたしますが、おそらく作り直しになると考えていますので、方針をご指示いただければと思います。

[タイタン装備](https://github.com/Helestia/moecoop-data/commit/5625e502402e73cc5de03fe405aee3613c7feccd#diff-0906c84c0c9081e904163268d27b96e6)
[楽器類１](https://github.com/Helestia/moecoop-data/commit/9d9c4555c6a2976bf3f6f784033df5c8359dd89f#diff-96ab4e163f4ee03aaa4d1051aa51d204)　/　[楽器類２](https://github.com/Helestia/moecoop-data/commit/4d2027417d50ded3ecb5ea6dd2570813f7a10caf)
[アセット類](https://github.com/Helestia/moecoop-data/commit/35b643ea2e998a9ecdbc007cef1811c7a8fc9ef1)

**Comment by coop-mojo** [comment]
ありがとうございます！

- タイタン装備と楽器に関しては、単にコンバート元の MoE wiki の装備のページに載っていなかったのが原因だと思います
  - 一番最初は、データは wiki の情報を変換して入力していました。
- アセットに関しては、アセット特有の属性をどうするか(高さ、重ねて置けるかをどう調べればいいか、など)をどうしようと考えて、そのまま止まってしまっていました。

タイタンでの性能や楽器としての属性などをどう置くか、という問題はともかく、アイテム情報として追加することには全く反対はありません(専用項目はなくても知恵袋で表示はできる、はず)。

とりあえず、以下の方針で PR を作っていただけるとありがたいです！
- タイタン装備とアセットに関しては、`種類` フィールドは `武器` や `防具`  など、普通のアイテムとしての属性にしておく
  - タイタンで使える、楽器として使用できるなどの情報は付けない or `備考` フィールドに記載する程度にしておく
  - 固有のデータ(タイタンでの性能など)は当面は用意しない
    - こういうデータなら十分じゃないか？という提案はお待ちしております！
- アセットに関しては、`種類` フィールドの値は `アセット` でお願いします (種類フィールドだけは用意済み)
- タイタン装備、楽器、アセット追加はそれぞれ別 PR だとありがたいです。
  - 小さな PR の方がレビューやマージが簡単で、知恵袋のウェブ版に反映するのも比較的早く行いやすいです。

よろしくおねがいします！

**Comment by Helestia** [comment]
ご回答ありがとうございます。

#### ジャスパー専用装備について
まずはジャスパー専用装備類について、いったんこちらでまとめたうえでpull requestを送付いたします。
「装備」用のJSONファイルの項目に「ジャスパー用」の文字をすべてのアイテムに対して付与と言う形で作業を行います。

#### 楽器について
一部の武器について、武器「音楽」が新設されています。（アタックなどに利用できるか不明）
- ./resource/アイテム/武器/楽器.json
- ./resource/武器/楽器.json
この2つを新設してもよろしいでしょうか？

#### アセットについて
とりあえずですが、現状の私が作成したファイル形式でよろしいでしょうか？
- [アイテム項目](https://github.com/Helestia/moecoop-data/blob/addRecipeItems2ItemAndEquipment/resource/%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0/%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88.json)
- [アセット項目](https://github.com/Helestia/moecoop-data/blob/addRecipeItems2ItemAndEquipment/resource/%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88/%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88.json) （ディレクトリを新たに1つ作成しています。）

**Comment by coop-mojo** [comment]
> wikiをベースにするのであれば、./アイテム/ジャスパー.jsonにアイテム情報を登録し、./防具/ジャスパー,jsonを作成する形でよろしいでしょうか？

はい！


>    ./resource/アイテム/武器/楽器.json
>    ./resource/武器/楽器.json
> この2つを新設してもよろしいでしょうか？

はい！

> アセットについて

アセットのアイテム項目とアセット固有項目もそれで問題ないです！
ただ、アセット固有項目に関しては[サーバー側](https://github.com/coop-mojo/moecoop-server)のプログラムの対応も必要なため、表示させるのはしばらくお待ち下さい…
moecoop-data に追加するのは PR いただければやります！

**Comment by Helestia** [comment]
お返事ありがとうございます。
ジャスパー、アセットについての作業内容については了解いたしましたので、作業を開始いたします。

アセット専用項目を生協の知恵袋に反映させることについては、私は特に急いではおりませんので、いつでも構いません。
（私もmoecoop-dataを利用してツール作成したいなと考えてのissueやリクエストですので…）

楽器の防具については、既存部位（腰装飾・腰装飾）ではなく、こちらも`./防具/楽器.json`を作成する形でよろしいでしょうか？

作業自体はある程度終わっているのですがログがクッチャグチャですので、いったんmasterからブランチ切ってきれいなログにしたうえでPL送らせていただきますね;;

**Comment by coop-mojo** [comment]
> 楽器の防具については、既存部位（腰装飾・腰装飾）ではなく、こちらも./防具/楽器.jsonを作成する形でよろしいでしょうか？

そうですね。新設してください！

**Comment by coop-mojo** [comment]
全部マージしたので close します！
