### ISSUE TITLE
複製レシピの取り扱いについて

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#13]
複製の生産について、現在レシピのファイルがないようです。

すべてのテクニックを登録し、秘伝の書などのアイテムもすべて登録していくとなると膨大な数になり、このプロジェクトを用いた別のプロジェクトのパフォーマンスなどを考えるとあまりやりたくないかなと思います。
（あと単純に技書を登録していくと今後も発生する課金装備に付随したテクニックなどもメンテナンスしていく必要があり、項目が膨大でメンテナンスが追いつかないという問題もあります…）

技術書やノアピース、究極奥義書を除いてレシピノートやソウルオブシリーズ、グリモワールなどの一部のレシピのみ登録するという手もあるかとは思います。
どのような方法がいいかご検討いただけませんか？

**Comment by coop-mojo** [comment]
> すべてのテクニックを登録し、秘伝の書などのアイテムもすべて登録していくとなると膨大な数になり、このプロジェクトを用いた別のプロジェクトのパフォーマンスなどを考えるとあまりやりたくないかなと思います。
（あと単純に技書を登録していくと今後も発生する課金装備に付随したテクニックなどもメンテナンスしていく必要があり、項目が膨大でメンテナンスが追いつかないという問題もあります…）

現在複製レシピ情報がない理由が、まさにご指摘の通りの理由です…

ざっと確認しましたが、[複製レシピ](http://moewiki.usamimi.info/index.php?%A5%B9%A5%AD%A5%EB%2F%C0%B8%BB%BA%2F%CA%A3%C0%BD)の古文書以下のレシピであれば、それなりに対応できそうです。

**Comment by Helestia** [comment]
ご回答ありがとうございました。そして状況について了解いたしました。

取り急ぎ作ったものがすでにあるので、いったんまとめてpull requestを送らせていただきます。
