### ISSUE TITLE
レシピ：コンバイン後の材料の消費方法を知る方法がない

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#18]
#14 複製レシピ作成

上記pull requestのレビュー中に発展した議題ですが、本題の複製レシピ登録とは外れてしまうため、こちらに別件としてissueを建てることとなりました。

アイテムを生産した際、素材として使用したアイテムはコンバイン終了後に下記のいずれかのパターンに分岐します。

- 使用したアイテムは消失します。（ほとんどの素材はこのパターンとなります。）
- 使用したアイテムは消失せず、再度別の生産などに使用できます。
また、複数セット生産する場合でも、このタイプのアイテムは1つで生産できます。
（タイヤキメーカーや大根おろし生産時の金物ヤスリが該当）
- 生産に成功した場合、使用したアイテムは消失しません。生産に失敗した場合は消失します。
（多くの複製系レシピの原本が該当）
- 生産の成功・失敗にかかわらずアイテムが持つ耐久値を消費します。
耐久値を使い切った場合、アイテムが消失します。
（ソウルオブシリーズを用いた生産や、麺生成時のウッドゥンスティックなどが該当。）

現在はレシピの備考項目で文章としてこれらの項目を管理していますが、もうちょっとスマートな管理方法がないか検討したいです。

以下、いくつか案があると思います。
文章での説明はする側もされる側も難しいでしょうから、例示などを多用したほうがいいと思います。

issueの〆などは@coop-mojoさんにお任せします。

**Comment by coop-mojo** [comment]
#14 のコメント欄で書いた案を再掲します。

> - ソウル系などを`消耗品`カテゴリのアイテムに分類し、消耗品カテゴリの専用フィールドに `使用可能回数` (optional: デフォルトは1)を追加
> - レシピ側のデータ構造を拡張して、レシピの生産素材のフィールドに、消費方法を区別するためのフィールドを追加する

**Comment by coop-mojo** [comment]
とりあえず前提として、備考欄だと都合が悪い理由も挙げておきます。
- 備考欄の文字列を解析する必要がある
  - せっかく JSON などの構造的なデータ構造で情報を表現しているのに文字列解析させたらデータ提供者として負け！

現状だと、本来フィールドになってほしいけど備考欄に入っているものには以下が挙げられます。それぞれの解決はこの Issue の範囲を超えるので、必要に応じて別 Issue で！
- 生産後の素材の扱い (この Issue)
- 同時生産の最大数 (ラッシーなど)
- 楽器やジャスパー装備など、通常の装備品としての効果以外の特殊効果があるもの (関連:#12)

**Comment by coop-mojo** [comment]
> - ソウル系などを消耗品カテゴリのアイテムに分類し、消耗品カテゴリの専用フィールドに 使用可能回数 (optional: デフォルトは1)を追加

これは、例えば `消耗品/消耗品.json` などの名前で以下の内容のファイルを追加するというものです。
ただ、現状だとポーション系も消耗品カテゴリに分類してしまっているため、アイテムの分類を見直す必要は出てくるかもしれません。

```json
[
    {
        "名前": "ソウル オブ ヤマト",
        "使用可能回数": 100
    },
    ...
]
```

> - レシピ側のデータ構造を拡張して、レシピの生産素材のフィールドに、消費方法を区別するためのフィールドを追加する

こちらは、例えば以下のようにレシピのデータ構造に修正を加えるものになります。

```json
[
    {
        "名前": "ソウル オブ エキゾチシズム",
        "材料": { // この部分に変更あり
            "未記入のスクロール": {
                "個数": 50,
                "消費方法": "消費"  // 取りうる値は `消費`、`耐久減少`、`失敗時消費`、`消費しない`
            },
            "インク" :  {
                "個数": 1,
                "消費方法": "消費"
            },
            "ソウル オブ エキゾチシズム" :  {
                "個数": 1,
                "消費方法": "耐久減少"
            },
        },
        "生成物": {
            "ソウル オブ エキゾチシズム": 1
        },
        ...
    },
    ...
]
```
問題点は、単なるフィールド追加ではなく構造変更なので、既存のレシピもまるごと修正が必要な点と、moecoop-server などの moecoop-data を利用しているアプリケーションに影響が出る点です。

とはいえ、真面目に問題を解決するなら、この変更はおそらく避けられないと考えています。

**Comment by Helestia** [comment]
既存案の提示、ありがとうございました。

> とはいえ、真面目に問題を解決するなら、この変更はおそらく避けられないと考えています。

同意いたします。作業量はレシピの修正、プログラム側の修正、APIの修正と多岐にわたることになるとは思いますが…素直にデータを設計した場合、そのような解法になるのが自然かとは思います。
もし私も開発者が自分だけである場合、ご提示いただいたようにレシピの材料オブジェクトの構造変更をメイン路線としてやりたいかなと考えますが…ほかの方がAPIを利用している場合、そちらに影響が出ることが懸念されます。

また、材料をすべてオブジェクト化するので、どうしてもファイルサイズも肥大化しがちになるというのもデメリットの１つかなと考えます。

### 後方互換性をぎりぎりまで維持する場合のプラン

レシピ側はいじることができる場所は素材アイテム名くらいしかないので、そちらを加工する形になると思います。
```
[
    {
        "名前": "ソウル オブ エキゾチシズム",
        "材料": { 
            "未記入のスクロール": 50,
            "インク" : 1,
            "ソウル オブ エキゾチシズム *耐久消費*" :  1
        },
        "生成物": {
            "ソウル オブ エキゾチシズム": 1
        },
        ...
    },
    ...
]
```
> せっかく JSON などの構造的なデータ構造で情報を表現しているのに文字列解析させたらデータ提供者として負け！

結局ここに引っかかるので…状況は変わらないかもしれませんが、耐久消費と全消費でアイテム側として異なる扱いができるというところが利点になりますかね。

#### この場合のアイテム情報の参照について

1. アイテム`ソウル オブ エキゾチシズム *耐久消費*`を登録する
2. アイテム`ソウル オブ エキゾチシズム *耐久消費*`から`ソウル オブ エキゾチシズム`を関連付けられるようなjsonファイルの新設

1の場合はゲーム内に存在しないアイテムを登録するということになり、また重複登録でもあるため採用しづらいですが、既存のシステムを全く壊さずに対応が可能です。
2の場合は既存システム側の改修が必要ですが、最悪改修しなくても(ある程度は)動作します。しかし新設したjsonファイルのメンテ漏れなど、別系統の問題が発生する恐れがあります。

#### 耐久値情報について

耐久情報は現在、装備専用のjsonファイルに登録されているため、ソウルオブシリーズとスケッチ道具については登録場所がないのがネックになります。
アイテム情報に登録する場合、装備類と登録場所が異なるためプログラム側が複雑になりかねないことと、jsonファイルのメンテミスの恐れ（装備品の耐久をアイテム側に登録してしまうなど）が懸念されるかなと思います。
装備側の耐久情報もアイテム側に持ってくる、あるいは一般アイテムであるソウルオブシリーズなどの耐久情報を格納する別のファイルを新設することを考えたほうがいいかなと思います。（アイテム種類`耐久付一般アイテム`を新設するなどすれば、その種類のアイテムは新設jsonを参照するなどの対応も取れるかなと…）

##### 余談

アイテムの分類「一般アイテム」と「その他」の違いがよくわかりませんね…wiki情報を解析したのが大元にあるのでしょうからしょうがない問題なのかもしれませんが、使い分けが難しそうです。
ソウルオブシリーズが「その他」、スケッチ道具が「一般」にそれぞれ登録されています。

私は別案を提示しましたが、@coop-mojo様のご提示いただいている方針（レシピの「材料」項目の大改修）について、私個人としては大いに賛成です。作業ボリュームが膨大なのと、プロジェクト利用者・サーバーAPI利用者が何人くらいいるのか・連絡はつくのかあたりが方針選定の基準になるかと思います。

**Comment by Helestia** [comment]
一晩寝て起きたら思いついただけの戯言です。

レシピ/複製.json
```
[
    {
        "名前": "ソウル オブ エキゾチシズム",
        "材料": { 
            "未記入のスクロール": 50,
            "インク" : 1,
            "ソウル オブ エキゾチシズム" :  1
        },
        "材料特殊消費" : {
            "ソウル オブ エキゾチシズム" :  "耐久現象"
        },
        "生成物": {
            "ソウル オブ エキゾチシズム": 1
        },
        ...
    },
    ...
]
```
この形であればアイテムの重複登録なども不要になりますね。
一般アイテムの一部に耐久値を設定する必要はまだ出てきますが…

ご検討いただければ幸いです。

**Comment by coop-mojo** [comment]
`材料特殊消費` の案に +1 です！ 特殊消費するレシピのみ変更すれば良いというのと、破壊的変更ではないのがとても良いです。

`"ソウル オブ エキゾチシズム *耐久消費*"` などのアイテム名に情報付与する方法は、文字列解析したくない云々のポリシーの問題の他に、moecoop-server 側に変更が必要になるので避けたいです。

 > アイテムの分類「一般アイテム」と「その他」の違いがよくわかりませんね

おそらくファイル名のことを指して `分類` と言われているのだと思いますが、このファイル名自体には大きな意味はありません(moe wiki と対応がある程度取れているのでざっくり探しやすい、という利点はなくもないですが…)。

各アイテムの汎用情報と、武器や防具、アセットなどの種別ごとの専用情報の紐付けは、`種類` フィールドのみで行えるようになっています。
moecoop-data では、現状は以下のアイテム分類 (== `種類` フィールドの取りうる値) を使用しています。
- 不明
  - どれに分類するべきかわからないもの (とりあえずアイテムとして追加だけしておく場合などに使う)
- 食べ物
- 飲み物
- 酒
- 消耗品
- 武器
- 防具
- 弾
- 盾
- アセット
- その他
  - 上記のいずれにも含まれないもの

上に転載した
> ソウル系などを消耗品カテゴリのアイテムに分類し、消耗品カテゴリの専用フィールドに 使用可能回数 (optional: デフォルトは1)を追加

は、ソウル系の `種類` フィールドの値を `その他` から `消耗品` に変更し、また消耗品の専用情報として `使用可能回数` フィールドを追加する、という案になります。

**Comment by Helestia** [comment]
ファイル名・ファイル分けはアイテム分類上意味はないのですね、了解いたしました。
wikiには消耗品の定義は、

- useで使用できる課金アイテム（ペット・レシピ・花びらや液等）、飲食物以外のアイテム
- 何らかのテクニック・魔法の触媒（ペット系など別枠あり）
- 修理素材

となっていますが、修理素材を消耗品としながら各種鉱石は専用ページ、クリスタルは一般アイテム扱いですかね。少々区分が大雑把かもしれません。

現状でもワーシップドールがmoecoop上ではその他となっているため、moecoopとしての分類とwikiのページとでは分けて考えたほうがよさそうです…が…アイテムメンテの敷居が上がっちゃいますよねこれ…

今回生産レシピ関係で耐久値の新設が必要なアイテムは下記

- ソウル オブシリーズ
- スケッチ道具

それ以外に装備品・アセット以外で耐久系情報を持っているアイテムは思いつくだけで`大きな染色液`がありますかね。

wikiベースの分類ではなく、また別の分類をmoecoopで作ったほうがいいのかもしれませんね。難しい；；

**Comment by coop-mojo** [comment]
> wikiには消耗品の定義は、

そもそも wiki に消耗品の定義が書いてあるのを知りませんでした！
moecoop-data での分類は既に独自のものです。ゲームの世界観ベースの分類ではなく、ゲームシステム上の役割(装備できる、 USE できる、など)を元に分類しているつもりです。
例えば、ノアダストなどの触媒系は wiki では消耗品ですが、USE もできず使用可能回数などのカウントもないため、moecoop-data では `その他` 扱いにしています。

今の所、消耗品としては 「USE できる」 or 「使用可能回数がある」ものを分類しようと考えています。他の USE できるものとの違いは以下のとおりです。

- 飲み物
  - USE できる
  - USE すると 潤喉度 が上昇する
- 酒
  - USE できる
  - USE すると 酩酊度 が上昇する
- 消耗品 (今回新設？)
  - USE できる or 使用可能回数がある
  - USE した場合の効果をどう分類するかは要議論 (以下はありうるパターン)
    - ペット取得 (システムメッセージから考えると、箱もこれに該当)
    - PC にバフが付与される (花火など; 包帯はこれ？)

ただ、「USE できる」と「使用可能回数がある」はそれぞれ別の種類にしたほうが都合がいいかもしれません。
…両方を満たすアイテム(複数回 USE できる)なんてありましたっけ？手鏡？

**Comment by coop-mojo** [comment]
moecoop-data の現状の `消耗品` は `その他` と内部的には同じ扱い (固有フィールドがない) ため、これを機に整理したいですね。

**Comment by Helestia** [comment]
>そもそも wiki に消耗品の定義が書いてあるのを知りませんでした！

!!!
定義と言うよりは、[アイテムリストページ](http://moewiki.usamimi.info/index.php?%A5%A2%A5%A4%A5%C6%A5%E0%2F%A4%BD%A4%CE%C2%BE1)のこの部位ですかね…；；
![image](https://user-images.githubusercontent.com/68133854/89730142-11a1c800-da77-11ea-8468-c40d64b8ff42.png)

混乱させてしまって申し訳ありません。ほかに消耗品とは何かと決めてる場所が見つからなかったもので；；

> 「USE できる」と「使用可能回数がある」はそれぞれ別の種類にしたほうが都合がいいかもしれません。

こちらについては私も分けてしまったほうが都合がいいのでは？と考えます。手鏡…使ったことないですね＾＾；；
他のところについては異存ありません。どうもありがとうございます。

**Comment by coop-mojo** [comment]
手鏡は一回使い切りでした！
なので、現在未分類 (適切なフィールドを付与できていないもの)は以下の2つでしょうか。

- USE でき、一回 USE すると手元から消えてしまうもの。効果は以下のいずれか
  - USE した PC がアイテムを1個以上取得する
  - USE した PC のペットを呼び出す
  - USE した対象にバフを付与する
    - 薬などは、対象として自身以外を選べない属性が付けられている、と考えるとこのカテゴリに含めることができる

- 装備品や盾、アセットではないが使用可能回数(あるいは耐久値)が設定されているもの。ここに含まれるのは以下のアイテムのみ？
  - ソウルオブなんとか (3種)
  - スケッチ道具
  - 染色液(大)
  - 貴族の隠し金庫？ (使用可能回数がついているがアセットではなく、またこれを使ったレシピもない)

前者については `消耗品` カテゴリを導入するので問題なさそうですが、後者はカテゴリ導入するには少なすぎますね… (名前にも困る…)
`その他` カテゴリに使用可能回数 (デフォルトは 1)を追加する手もありますが、それはそれで処理が煩雑に…

もう少し考えてみます。

**Comment by coop-mojo** [comment]
タイトルを変更しました。
この Issue は複製レシピやソウル系などの材料の消費方法が特殊なレシピおよびアイテムに関するもので、例えば NG や HG などのグレードで生成物が変わるレシピなどの話は Issue の範囲外となります。

**Comment by Helestia** [comment]
タイトル表現が分かりづらかったですね。修正ありがとうございます。
私からの意見は出し切ったと思うので、以降は@coop-mojoさんに方針などはお任せしようかと思います。

作業は私のほうでも行えると思います。
何かありましたらこのIssueで指示ください。

**Comment by coop-mojo** [comment]
とりあえず、以下の方針にしようと思います。

- ソウル系などは `その他` として分類する
  - `その他` の固有フィールドとして `使用可能回数` (optional, デフォルト値は 1) を追加する
  - こちらで対応作業します
- 材料の消費が特殊なレシピに関しては `特殊消費` (議論中では `材料特殊消費` となっていたもの) フィールドを追加する
  - ただし #25 との兼ね合いで対応作業はまだしません
  - #25 で方針を決めてから、こちらの作業は行うことにします

**Comment by coop-mojo** [comment]
上記２つが実装された段階で、この Issue は close しましょう！

**Comment by coop-mojo** [comment]
前者の対応は #27 で行いました！

**Comment by Helestia** [comment]
作業方針、および作業内容について了解いたしました。
ご対応ありがとうございます。

装備品類の使用可能回数については、wikiでは[こちら](http://moewiki.usamimi.info/index.php?%BB%A8%B3%D8#y0d09749)にあります。

> - 消耗度表示が最初に1減るのは1回目or11回目or21回目or31回目（武器種類・材質による）

耐久値から使用可能回数を逆計算するのは何か難しそうですね…
最初に1減るという部分を固定で持つのであれば、使用回数を直接もつのと大差ないですしね
生産に使用する装備類で耐久を消耗するのは今のところ2種のみです。
プログラム的には固定で持っちゃってもいい部分ですかね…
- ウッドゥン スティック…料理　麺・蕎麦・十割そばの生産に使用
- カッパー ナイフ…裁縫　スクロール素材の生産に使用

**Comment by coop-mojo** [comment]
#25 は処理系側の対応待ちとしましたが、#25 をこちらのアクションだけでは解決できなくなったため、この Issue は上の方針通りに `特殊消費` フィールドの追加作業を進めることにします。

でも作業は @Helestia さんにお願いしてもいいですか！

---
以下は `特殊消費` フィールドの説明です。
- 型はオブジェクトで、キーはアイテム名、値は各アイテムの消費方法を表す
  - キーは `材料` フィールドに含まれるアイテム名でなければならない
- 消費方法は以下のどれかひとつ
  - `消失`
    - 成功、失敗を問わず、消えてなくなるもの
    - デフォルト値、省略可
  - `消費`
    - 上で `耐久減少` となっていたもの。アイテムによっては`使用可能回数`を参照するため、名前を変更しました
  - `未消費`
    - 成功、失敗を問わず、消失も消費もしないもの
    - タイヤキメーカー など
  - `失敗時消失`
    - 成功時には失敗時に消えてなくなるもの
    - 複製レシピの原本など
- `材料` フィールドに含まれる全てのアイテムの消費方法が `消失` の場合、`特殊消費` フィールド自体を省略できる
  - つまり、ほとんどのレシピは修正の必要がない

---

以下、追加用サンプルです。

```json
[
    {
        "名前": "ソウル オブ エキゾチシズム",
        "材料": { 
            "未記入のスクロール": 50,
            "インク" : 1,
            "ソウル オブ エキゾチシズム" :  1
        },
        "特殊消費" : {
            "ソウル オブ エキゾチシズム" :  "消費"
        },
        "生成物": {
            "ソウル オブ エキゾチシズム": 1
        },
        ...
    },
    ...
]
```

**Comment by coop-mojo** [comment]
> 装備品類の使用可能回数については、wikiではこちらにあります。

リンク先で重要なのは消耗度表示についての記述ではなく、むしろ `消耗度の減少` にある以下の記述ですね。

> - 武器
>   - 40回使用するごとに1減少

つまり `ウッドゥン スティック` (初期消耗度 10) の場合は400回、`カッパー ナイフ` (初期消耗度 27) の場合は1080回使用できることを機械的に計算できます (ウッドゥンスティックに関してはゲーム内の `装備耐久度表示` ウィンドウと突き合わせて確認済み)。

**Comment by Helestia** [comment]
> #25 は処理系側の対応待ちとしましたが、#25 をこちらのアクションだけでは解決できなくなったため、この Issue は上の方針通りに 特殊消費 フィールドの追加作業を進めることにします。
> でも作業は @Helestia さんにお願いしてもいいですか！

了解いたしました。作業を始めます。おそらく今日中には準備ができると思いますので、完了次第PRを起こさせていただきます。

-----

>> - 武器
>>     - 40回使用するごとに1減少

>つまり ウッドゥン スティック (初期消耗度 10) の場合は400回、カッパー ナイフ (初期消耗度 27) の場合は1080回使用できることを機械的に計算できます (ウッドゥンスティックに関してはゲーム内の 装備耐久度表示 ウィンドウと突き合わせて確認済み)。

大まかにはそのような計算で問題ないのですが、最大消耗度→1つ減少までの使用回数と、残1から0(消失)までの回数は別になります。
最大耐久値を使用回数に変換する式としては下記のような表現になると思います。

使用回数 = (1 or 11 or 21 or 31) + 40 * (最大耐久値 - 2) + 79

(1 or 11 or 21 or 31) ←この部分が`消耗度表示が最初に1減るのは1回目or11回目or21回目or31回目（武器種類・材質による）`を反映
最後の79が`消耗度が1から0（壊れるまで）になるまでは79回必要`を反映させています。
リンクのwikiページに素材別の表が添付されていますが、ウドゥンスティック（木）は410、カッパーナイフ（銅）は1100回使用できるようです。

**Comment by coop-mojo** [comment]
どちらかというと info 欄の耐久値の方が概算だと考えているのですが、だとすると wiki にあるウドゥンスティックの 410 回の説明が付きませんね…

時間がある時に実際に素振りして確かめてみます。

**Comment by coop-mojo** [comment]
素振りしました！
複数回やって、ウドゥンスティックが410回で壊れるのを確認しました！
これからカッパーナイフでも確認します！

**Comment by coop-mojo** [comment]
カッパーナイフ1100回で壊れました！(試行回数1回)

**Comment by Helestia** [comment]
わざわざ検証ありがとうございます…本来であれば私がするべきだったかもしれませんね。

ただ、この情報をこのプロジェクトで管理するよりは、利用する各プログラムが個別に持つべきデータのようにも思えたりします。
カッパーナイフやウッドゥンスティックの装備情報に使用回数を記載するのも違うような気がしますし…
このプロジェクトを利用するプログラム側が固定で持つとかするべきことなのかもしれません。

混乱させてしまってすいませんでした。

> 上記２つが実装された段階で、この Issue は close しましょう！

8/16に指示いただいた作業は、一通り完成済みですので、このIssueはクローズですかね？
最終判断については@coop-mojoさんお願いします。

**Comment by coop-mojo** [comment]
> この情報をこのプロジェクトで管理するよりは、利用する各プログラムが個別に持つべきデータのようにも思えたりします。

上の話は、そもそも管理するデータにするべきなのか、というのを考えるための検証のつもりでした。
単純に消耗値だけから計算できるのであれば、計算式だけ明らかにしてデータとして保持する必要はないはずなので。
実測値と wiki の情報から判断するに、結論はまだ出せなさそう、というのが私の見解です(素材ごとに内部データがあると仮定するとトレント上位弓など例外がありすぎますし、何より使用回数についてそんなデータを導入する利点が見えません)。

この Issue に関しては一旦 close して、使用回数の検証などは別の場所でやって、結果が出たら wiki の方に反映させることにします。

ともあれ、この Issue も含め、色々ご協力感謝です！
また何か要望などあればお知らせくださいな！
