### ISSUE TITLE
アイテム：課金アイテム/グラフィック装備のjsonファイル構造について

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#19]
[/resource/アイテム/課金アイテム/グラ装備1.json
](https://github.com/coop-mojo/moecoop-data/blob/master/resource/%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0/%E8%AA%B2%E9%87%91%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0/%E3%82%B0%E3%83%A9%E8%A3%85%E5%82%991.json)などにおいて、ほかのjsonファイルはルートがarrayなのに対して、この課金アイテムフォルダ内のjsonファイルのルートは連想配列になっているようです。
レイアウトが異なるのには何か理由があるのでしょうか？

##### 余談
個人的にはこのような用途では連想配列（課金アイテムフォルダ形式）のほうが適していると思います。理由は下記の通り。

1. array形式では「要素の順序」が意味を持ちますが、アイテム情報については順序を利用するような用途が想定できません。
2. array形式では同じ名前のアイテムを2重で登録してもエラーとなりません。（添え字のkeyが異なるため）
連想配列の場合、同名のkeyを登録すると構文エラーですので、対応したテキストエディタはエラー表示を行います。

**Comment by coop-mojo** [comment]
> レイアウトが異なるのには何か理由があるのでしょうか？

これ、多分課金アイテム以下は古いデータ構造のままになってます。直すべきですね。

なぜ moecoop-server さんはエラーを出さないのか…

> 個人的にはこのような用途では連想配列（課金アイテムフォルダ形式）のほうが適していると思います。

私も開発当初はそう思っていたため、[初期のデータ](https://github.com/coop-mojo/moecoop-data/commit/7705faa31a6d050945836e2289acafe9c7d1c471)では連想配列形式でデータを保存していました。
しかし、開発中に以下の理由により、データ構造を今の配列形式に変更しています。
- JSON <-> 構造体 のシリアライズ・デシリアライズを行う既存の JSON ライブラリのサポートが限定的になってしまうため、キー部分をフィールドに挿入するコードを自分で実装する必要が出てきてしまう
  - 例えば、アイテム情報をプログラム上で表現するときは、以下のように和名、英語名などをフィールドとして持つ構造体(あるいはクラス)として定義するのが自然だと考えられます(以下はD言語風の擬似コードですが、他の言語でもそれほど変わりません)。
    ```d
    struct アイテム情報
    {
        string 名前;
        string 日本語名;
        ...
    }
    ```
    - 既存の JSON ライブラリなどは、以下の JSON オブジェクトから上の `アイテム情報` 構造体のオブジェクトに直接変換する機能をサポートしているものが多いです(moecoop-server でも利用しています)。
      ```json
      {
        "名前": "ロースト スネーク ミート",
        "英名": "Roast Snake Meat",
        ...
      }
      ```
    - 一方で、以下のようにキー名にアイテム名を入れる方式の場合、ライブラリのデシリアライズ機能をそのまま活用できない場合が多いため、その部分を自分で新たに実装する必要があります。
      ```json
      "ロースト スネーク ミート": {
        // 情報の重複を避けるため、オブジェクトに `名前` は含めない
        "英名": "Roast Snake Meat",
        ...
      }
      ```
  - キー名に加えて value 側のオブジェクトにも名前を追加する方法もありますが、情報が重複するためデータのメンテナンスコストが増加します。
  - キー名重複に関しては、どうせ利用側のプログラムで検証するから特に問題にはならないと考えました。また、キー名の重複確認とデシリアライズ処理の独自実装では、キー名重複確認の方が開発者側のコストは少ないだろう、というのが当時の判断だと思います。

- #20 で指摘されている同名の別アイテムを、同名のまま登録する手段が**なくなる**
  - 配列方式であれば、例えば内部でアイテムを一意に識別する ID などを導入することで、`カーミラ ヘアバンド` (課金の方) と `カーミラ ヘアバンド` (生産の方) を、同名のまま区別することも可能です(現状ではそうなっていませんが)。
  - 連想配列形式にすると「片方の名前を変える」しか選択肢がないのに対して、配列方式では「片方の名前を変える」と「内部IDなどを導入する」の2つを選択肢として残しておけます


---
このプロジェクト、開始から4年も経っているのですね…うごごご…

**Comment by Helestia** [comment]
ご回答ありがとうございました。
詳しい検討をなされた結果だったのですね…

趣旨については了解いたしました。
課金装備については、私のほうで作業したほうがよろしいでしょうか？（言い出しっぺの法則）
もしその場合は、key名を名前フィールドに移植した配列を用意するだけでよろしいのでしょうか？
他に注意点などがないようでしたら、軽くツール作ってやっちゃいます。

**Comment by coop-mojo** [comment]
> 課金装備については、私のほうで作業したほうがよろしいでしょうか？

おねがいします！

> key名を名前フィールドに移植した配列を用意するだけでよろしいのでしょうか？

はい。それで大丈夫です！

**Comment by coop-mojo** [comment]
> なぜ moecoop-server さんはエラーを出さないのか…

古いデータ構造用の fallback 処理を使って読み込んでたからでした。
