### ISSUE TITLE
アイテム：ガチャ品と生産品の区別について

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#20]
現在、一部のレシピで生産品のアイテム登録がなされていないアイテムについて、PRを行えるように作業中です。

そこで、隠密半被について調査（アイテム側が隠密法被と誤字？）を行っていました。

一部の装備アイテムはガチャで実装された後、生産可能となる課金アイテムが生成され、
生産品とガチャ品が別で存在するような形となっています。

それだけであれば特段問題はないのですが、付加効果が異なるアイテムが存在するようで、単純にアイテム名で登録するわけにはいかないようです。

今回の例であれば、このような差があります。

- ガチャの隠密装備は、初期では装備効果がなく、精錬可能で精錬した場合に装備効果が発生する。
- 生産品は装備効果があらかじめついている。

一部アイテムには(ガチャ品)などの記載があった気がしますが、どういった登録方法を行えばいいかご指示いただければと思います。

参考：[公式・グラフィック装備生産](https://moepic.com/sp/material/index.html)

**Comment by coop-mojo** [comment]
現状では、同一名称の別アイテムは、アイテム名を変更して登録しています(アイテム名末尾に `(染色可)` を付与するなど)。
ガチャ品と生産品のどちらかに、`(ガチャ)` あるいは `(生産)` と付けるのがいいと思います。

とりあえず、今回は生産品の方に `(生産)` を付ける方針でどうでしょう？

**Comment by Helestia** [comment]
回答ありがとうございます。
それでは、グラフィック装備系の生産アイテムすべてに対して(生産)と付与する作業を行いまーす。
後日PRさせてもらいますので、恐れ入りますがその際にレビューをお願いします。

**Comment by Helestia** [comment]
事前調査を怠っていたようで申し訳ありません。
再度確認させていただきたい内容がございますので、恐れ入りますが再回答をお願いします。

なお、この返信上ではガチャと書くと、アイテムショップ購入やマイレージなどの
別口入手手段を軽視している印象を受けるため、
「課金品」と記載します。（秘伝の本が課金アイテムなのは一旦棚上げしますｗ）

1. 生産品と課金品が同名の物について
現在実装されている秘伝の本(アイテムショップで販売されているグラ装備の生産素材）は8種類で、
内容は[この公式サイト](https://moepic.com/sp/material/material_08.html)にある通りです。
そのうち、下記3種については生産品と課金品で名称が全く異なっていました。よって修正対象は残り5種です。
    - ダークナイト装備（課金品：ダークナイト ヘルム　生産品：漆黒の兜）
    - シルフィード装備（課金品：フェザーハット オブ シルフィード　生産品：風の羽根帽子）
    - ナイトロード装備（生産品2点のみで、課金品には存在しない装備）
2. 下記アイテムについて、既存のjsonファイルの課金品のほうに`（ガチャ）`、あるいは`（もえガチャ）`と記載されています。
    - 隠密装備（隠密の傘・半被・肩当・腰当・虎の股引き・豹柄の腰巻・ねずみ草履・黒猫のお面）
    - スカウト防具（ヘルメット・チュニック・パンツ・ブーツ・グローブ・ショルダー・プロテクター）
    - 刀剣武器　ヒューネラル ブレイド
3. 念のため、生産でフォルダ内検索したところ、現状ではヒットしませんでした

以前の返信では事前情報がない状態で判断を仰いだため、生産側にタグをつける方針になりましたが、既存で一部ガチャとついていること、生産のタグが1つもないことなどが分かりましたので、再判断をお願いいたします。

**Comment by coop-mojo** [comment]
確認ありがとうございます！

> 下記アイテムについて、既存のjsonファイルの課金品のほうに`（ガチャ）`、あるいは`（もえガチャ）`と記載されています。 

あら。それなら `（生産）` よりも、既存の `（ガチャ）` に統一するほうが良さそうですね。
`（ガチャ）` と `（もえガチャ）` は、`（ガチャ）` の方にまとめてしまうのがよさそうですが、これは表記ゆれ修正の別 Issue にしたほうが良さそうです。

**Comment by Helestia** [comment]
了解いたしました。それでは下記方針で今日の夕方以降に作業を開始します。

1. 課金品と生産品が同名で存在する場合、課金品側のアイテム名に識別ラベル` (ガチャ)`と追記する。
2. 既存の入力を踏襲し、付与する識別ラベル` (ガチャ)`は、下記の通りで行います。
    - アイテム名とラベルの間に半角スペースを1文字付与
    - カッコは半角小カッコ` (ガチャ)`で記入
3. 同名の生産アイテムが存在しない場合、このラベルは付与しない

今回、私のほうではグラフィック生産の公式サイト上に存在するアイテムについては作業を行います。
（隠密・スカウト・ヴァンパイア・大正ロマン・魂振の5シリーズ）
それ以外に課金と生産でアイテム性能が異なるなどあるかどうかは把握していませんが、
もし発見次第別作業としてPRを行います。
