### ISSUE TITLE
moecoop-data 内のデータ構造の形式的な定義がない

### ISSUE THREAD

**Issue by coop-mojo** [coop-mojo/moecoop-data#25]
関連した Issue に #24 がありますが、あちらは主に人間が読む情報源を想定しています。
この Issue は、プログラムによる自動的な検証が可能になるようなものが何も提供されていない問題を解決するためのものです。

---
現状では新規データなどを追加する際に、人間による心温まる目視か、[知恵袋サーバー](https://github.com/coop-mojo/moecoop-server)と直接組み合わせて動くかどうかを確認するくらいしかデータが正しい形式かどうかを確認する方法がありません。

例えば JSON Schema などによるアイテム情報構造の定義などがあれば、以下を行うことが可能になります。
- CI を用いた自動検証ができるようになる
  - 副次的な効果として、PR が CI を pass するかを Github 上で確認できるようになるため、レビューの負担を減らすことができる
- [VSCode などのエディタによるサポート](https://qiita.com/xx2xyyy/items/fc95d421ca2248535472#%E3%81%9B%E3%82%81%E3%81%A6%E6%89%8B%E5%85%83%E3%81%A7validation%E3%82%84%E8%A3%9C%E5%AE%8C%E3%81%8C%E5%87%BA%E6%9D%A5%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86)が得られる
- [入力フォームの自動生成](https://qiita.com/g0e/items/9a4f886897fd46f107a8#%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E3%81%AB%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B)などが可能になるため、今後データ入力の補助システムを作りやすくなる

---
VSCode によるサポートも得られるため、JSON Schema を追加する方針に決定。
以下は作業リスト:
- [x] その他 (#44)
- [x] アイテム一般 (#45, #47)
- [x] アセット (#49)
- ~~クエスト~~ (#50)
  - 色々考慮不足のためあとでやる
- [x] バインダー (#51)
- [x] レシピ (#52)
- [x] 売店 (#53)
- [x] 弾 (#72)
- [x] 武器 (#79)
- [x] 盾 (#80)
- [x] 防具 (#67)
- [x] 食べ物 (#81)
- [x] 飲み物 (#82)
- [x] 飲食バフ (#84)

**Comment by coop-mojo** [comment]
既知の課題としては、moecoop-data の一部のデータは JSON Schema と相性が悪い構造である点が挙げられます(おそらく他の schema でも同様)。
JSON Schema では、JSON object のキー名の定義や値の型などを指定できます。一方で、例えば以下のデータ構造中の `効果` オブジェクト内のフィールド定義などは自然な形で書くことができません。
```json
[
    {
        "名前": "HP/ST/MP 自然回復速度UP",
        "効果": {
            "HP": 85,  // <------ これ！！！
            "ST": 105,
            "MP": 85
        },
        "効果時間": 80,
        "グループ": "E"
    },
    ...
]
```

解決策としては、以下のように JSON Schema による validation を行いやすい形式に変更する方法があります。

```json
[
    {
        "名前": "HP/ST/MP 自然回復速度UP",
        "効果": [ // ObjectからArrayに変更する
            {
                "ステータス": "HP",
                "効果値": 85,
            },
            {
                "ステータス": "ST",
                "効果値": 105,
            },
            {
                "ステータス": "MP",
                "効果値": 85,
            }
        ],
        "効果時間": 80,
        "グループ": "E"
    },
    ...
]
```

これは破壊的変更になるため、moecoop-data を使うシステム側の対応も必要になります。

でもやったほうがいい。

**Comment by coop-mojo** [comment]
今の所、形式的な定義として[ JSON Schema](https://json-schema.org/) を使おうと考えています。

**Comment by coop-mojo** [comment]
簡単に手元で確認したところ、VSCode では日本語のパス名が含まれていると JSON Schema による validation が有効にならない様子…

**Comment by coop-mojo** [comment]
大きな利点である VSCode による動的チェックがこのままでは入らないため、問題が解決されるまでデータ構造の変更に関しては保留にします。

**Comment by Helestia** [comment]
なにか私の環境でjsonSchemaが何とか動いたので、ドラフトでPRを行いました。
恐れ入りますが確認をお願いいたします。

**Comment by Helestia** [comment]
今後のこのIssueの進め方について確認いたします。
#40に@coop-mojoさんからコメントいただいていますが、このIssue内で優先すべきはschemaの適用であり、その後構造変更について検討するという流れでよろしいでしょうか？

このプロジェクトのスキーマ対応とレイアウト変更について、不謹慎ながら楽しみにしており、このIssueが停滞するのは避けたいと考えています。

もし現状で何も作業をなされていないのであれば、下記を提案します。

- 全体的な方針
  - とりあえずたたき台がないと議論にもならないため、いったん私のほうで既存レイアウトに合ったSchemaの作成を行います。
  - レイアウト1件のスキーマが完了次第PRを行います。PR内で**既存の**レイアウトにスキーマがあっているかどうか確認して議論しましょう。
  - このIssueの続きか、あるいは別のIssueを立ててレイアウト変更については別途検討したほうがいいと思います。
- 私の行うたたき台作成の作業方針
  - アイテム名やbuff名などがkey名と指定されている項目については、`anyOf`で指定します。
  - ペットアイテムやステータス増減など、おそらく今後増減しないであろう項目はできうる限りスキーム対応します。
  - フォルダ構造は前回のドラフトPRでも使用した`./docs/schema/フォルダ名.json`とします。
  - 作業中に見つかったtypoなどは一度スキーマ上でエラーとし、別の修正PRを私のほうで行います。
- 現状このプロジェクトに存在するJSONデータ形式は14種類　以下は私のタスクリストとして利用。
  - [ ] その他
  - [ ] アイテム
  - [ ] アセット
  - [ ] クエスト
  - [ ] バインダー
  - [ ] レシピ
  - [ ] 売店
  - [ ] 弾
  - [ ] 武器
  - [ ] 盾
  - [ ] 防具
  - [ ] 食べ物
  - [ ] 飲み物
  - [ ] 飲食バフ

以上、よろしければお返事いただければ作業を開始します。

**Comment by coop-mojo** [comment]
> このIssue内で優先すべきはschemaの適用であり、その後構造変更について検討するという流れでよろしいでしょうか？

はい！

全体方針および叩き台作成の方針も、それで大丈夫です。
レイアウト変更については、それぞれ別に Issue を立てましょう。

タスクリストについては先頭に追加しておきます。

---

また、#39 についていくつか検証+調査したのでその結果を。
- macOS Catalina + VSCode (1.49.3) でも補完が効くことを確認しました！
- microsoft/vscode#69308 に、ほぼ同様の問題を発見しました。
  - 件の Issue の[コメント](https://github.com/microsoft/vscode/issues/69308#issuecomment-466910984)に
    > ... and you might have to encode characters.

    とあるため、おそらくパスを URL エンコーディングで表現する必要があるのは仕様だと考えられます。
  - 個人的には、以下の理由から `fileMatch` には URL エンコーディングされたパスのみで十分だと考えましたが、いかがでしょう？
    - URL エンコーディングのみで現状要求は満たせること
    - microsoft/vscode#69308 は対応されずに close されているため、日本語に関しても同様の方針になる(つまり、日本語のパスが使えるようにはならない)可能性が高い
    - 動かないコードを残しておくのは、読む側のコストがそこそこ高い

**Comment by Helestia** [comment]
> - microsoft/vscode#69308 に、ほぼ同様の問題を発見しました。

やはり英語が読めないとこういう問題にぶち当たったときにつらいですね…
ご確認ありがとうございました。

> - 個人的には、以下の理由から fileMatch には URL エンコーディングされたパスのみで十分だと考えますが、いかがでしょう？

個人的にはスキームの適用フォルダ名を日本語で明示されてないとurlデコードする手間があるから日本語名があったほうがむしろ読みやすいのかなとか思っちゃったりします。
しかしおっしゃる通り動作しないコードを置くのは美しくないこと、誰かが誤って動作するコードのほうを削除する恐れがあることなどを考慮するとないほうがいいかもしれませんね。
最終判断は@mojo-coopさんにお任せするとして、とりあえずは日本語フォルダ名は作らずにたたき台の作成を行います。

**Comment by coop-mojo** [comment]
> 個人的にはスキームの適用フォルダ名を日本語で明示されてないとurlデコードする手間があるから日本語名があったほうがむしろ読みやすいのかなとか思っちゃったりします。

その目的であれば、以下のようにコメントで補足するのが適切かと思います(通常の JSON では使えませんが、VSCode の設定ファイルはなんちゃって JSON のため、`//` を使った一行コメントが可能です)。
```json
{
    "json.schemas" : [
        // `fileMatch` 内の日本語は URL エンコーディングしないと動作しない
        // 詳細は以下を参照: https://github.com/coop-mojo/moecoop-data/issues/25
        {
            "fileMatch" : [
                // レシピ.json
                "/resource/%E3%83%AC%E3%82%B7%E3%83%94/*.json"
            ],
            "url" : "./docs/schema/レシピ.json"
        }
    ]
}
```

---
英語に関しては、Google 翻訳や DeepL に頼る手もあります。
機械翻訳だと文意が逆になったりいくつか文章飛ばして翻訳される時があるので、やっぱり自分で読めるのが一番ですが… (自分でも読めないと問題に気づけない)

**Comment by coop-mojo** [comment]
テスト用のスクリプト [`test.sh`](https://github.com/coop-mojo/moecoop-data/blob/master/test.sh) を追加しました。
Linux や mac などの Posix 環境用です(Windows だと WSL 上でないと動かない)。

動作には [ajv-cli](https://ajv.js.org/) (JSON schema の validator) と [jq](https://stedolan.github.io/jq/) が必要です。 

細かい挙動はともかく、`test.sh` および追加した CI には以下の特徴があります。
- `.vscode/settings.json` の設定を読んで validate を行う
  - つまり、例えば #51 で走る CI では、追加されたバインダー用の schema を使った `バインダー` ディレクトリ以下の validate も自動で行っています！ (テスト項目を手動で増やす必要がない)
- master へのコミットおよび PR 時に動作する
  - schema と VSCode 用の設定が提供されていれば、validate を通らなくなる変更がすぐに分かるようになります

CI が存在するリポジトリの場合、CI が pass するように PR を作る、というのが一般的なお作法ですね。
このリポジトリでもその方針でいきたいと思います。

---

余談ですが、CI を pass しないようなコミットや PR を受け入れてしまうと、「この PR は CI を pass してないけど、CI で表示されてるエラーは今回の変更とは関係ないから大丈夫」のような個々人の判断による CI 無視が横行し、急速に CI が腐ってしまいます(CI が信頼されなくなり役に立たなくなる)。
ご自身のリポジトリで CI 環境を作る+運用する場合はご注意ください…

---
以下、実装の簡単な解説です(スクリプト中にもコメントあり)。

- `.vscode/settings.json` の `json.schemas` の中を見て、検証用の schema ファイルと検証対象のファイル群を取り出す
  - `.vscode/settings.json` は `//` コメントを許可する[JSONC](https://komkom.github.io/) で書かれています
  - 後続の `jq` は JSON (コメントが文法的に書けない)しか受け付けないため、`grep -v` で雑に `//` が含まれている行を省いています
- 検証用の schema ファイルと検証対象のファイル群 の記述から、検証用の `ajv` 実行コマンド列を生成する
  - `./test.sh --dry-run` で、検証時に実行するコマンドを確認することができます
- `eval` で生成したコマンド列を実行し、schema を用いた検証を行う

**Comment by coop-mojo** [comment]
データ構造がある程度固まっているものに関しては、すべてスキーマが追加されました！
ありがとうございます！ @Helestia
