### ISSUE TITLE
盾：装備部位について

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#28]
どうやら最近は右手に盾を装備することもあるようです。
今のところ課金アイテムのみのようですが、装備部位の項目を作ったほうがいいのではないでしょうか？

参考：[MoE Wiki 盾装備](http://moewiki.usamimi.info/index.php?%A5%A2%A5%A4%A5%C6%A5%E0%2F%CB%C9%B6%F1%2F%BD%E2)

**Comment by coop-mojo** [comment]
そうですね。後で `装備箇所` フィールドを追加しておきます。

**Comment by coop-mojo** [comment]
#30 で対応しました！

**Comment by Helestia** [comment]
ご対応ありがとうございました！
