### ISSUE TITLE
売店ディレクトリ内のJSONに時代・エリアの情報を追加したい

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#40]
`resource\売店\`ディレクトリのファイルについて、現行ではファイル内容から販売員名を取得できますが、時代情報・及びエリアの情報が取得できません。
必然的にディレクトリ名やファイル名からゾーン情報を付与することになると思いますが、そのような書き方はつらいのでデータに含めたいです。

下記のいずれかを行いたいのですが、いかがでしょうか？

もし、#25 の作業の関係で販売物情報のレイアウト等を変更予定であれば、#25 の作業時の修正まで保留していただいてもかまいません。
おそらく販売情報のアイテム名をキーとした構造も問題になるかと思います。
https://github.com/coop-mojo/moecoop-data/issues/25#issuecomment-674376504

### プラン１．ファイル冒頭に追加※破壊的変更
```
{
  "時代" : "Present Age",
  "エリア" : "アルビーズの森",
  "販売員" : [
    {
      "名前" : "クリスティーナ",
      "販売情報" : {
        "ミニ ウォーター ボトル": {
          "価格": 15
        },
        ...
      }
      ....
  }]
}
```

### プラン２．各販売員に時代・エリア情報付与※フィールド新設
```
[
  {
    "名前" : "クリスティーナ",
    "時代" : "Present Age",
    "エリア" : "アルビーズの森",
    "販売情報 : [
      "ミニ ウォーター ボトル" : {
        "価格" : 15
      }
      ...
    ]
  }
  ...
]
```

以上、よろしくお願いいたします。

###### 余談

War AgeでのみNPC購入できるアイテムもありますが…専用通貨Jadeについてどうしましょうか。
時代情報が付与されればあとはプログラム側で対応でも良さそうな気はします。

**Comment by coop-mojo** [comment]
プラン2の方がよさそうなので、こちらでいきましょう！
#25 との兼ね合いについては以下がよさそうですが、いかがでしょう？

- この Issue と #25 は別途進める
  - 販売員のスキーマ対応はこの Issue を解決する PR のマージ後に行う
- #25 が一旦マージされた段階で、データ構造変更の議論+段階的なスキーマとデータの移行を進める
  - `fileMatch` を活用すれば、段階的に新スキーマを適用させつつ移行することが容易になるはず
  - なので、構造変更よりもまずはスキーマ適用を優先させたいです

> War AgeでのみNPC購入できるアイテムもありますが…専用通貨Jadeについてどうしましょうか

War Age のデータがない理由が、その問題を先送りにしたかったからです…
確かに pre/war などの時代区別だけ付けてプログラム対応でもよさそうですね。

**Comment by Helestia** [comment]
ではプラン２でとりあえず作業を進めます。

終わり次第PRを送らせていただきます。
