### ISSUE TITLE
装備アイテムの最大HP関連の付加効果プロパティの表記揺れをなくしたい

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#54]
Issue #25 に対応作業のため、現在スキーマの設定をしています。
そこで、装備アイテムの付加効果(最大HP+10等）について、いくつか表記ゆれがありました。

スキーマ設定を行う上でもこれらの表記揺れは統一したいと思います。
スキーマ設定を一度してしまえば、以降は発生しなくなると思いますので、どのような表記がいいか方針を決めませんか？

HPに関しては3パターンありました。
- `最大HP`
- `最大ＨＰ`
- `MHP`

ST,MPも同様の物があります。

なお、攻撃力や最大重量、攻撃ディレイなどはおそらく揺れはないと思います。（ざっくりとフォルダ内検索した結果ですが…）
防御力に関しては、食事buffに1点`"防御":10`と指定されているものがありましたが、残りは`"防御力"`でした。

スキーマ設定している以上、この手の問題はいくつか出てくると思いますので、その際のIssueの建て方なども都度でいいのか、まとめたIssueを一つ建てるべきか等教えていただけると助かります。

**Comment by coop-mojo** [comment]
> HPに関しては3パターンありました

`最大HP` にしましょう！
- `最大ＨＰ`: 全角よりは半角のほうが好み
- `MHP`: ぱっと見て何かわからない。`最大HP` の方は説明しなくても理解できる。
  - バフ辺りにも混ざってそうですね…

> スキーマ設定している以上、この手の問題はいくつか出てくると思いますので、その際のIssueの建て方なども都度でいいのか、まとめたIssueを一つ建てるべきか等教えていただけると助かります。

その都度 Issue を立てるのでいいと思います。下手にまとめてしまうと Issue が長くなり、後で追うのが難しくなるので…

**Comment by Helestia** [comment]
了解いたしました。
それではHP,MP,STの最大値上昇効果については`最大HP`等で統一しましょうか。

PRを日付が変わるまでには上げたいと思います。
