### ISSUE TITLE
武器・防具の設定項目確認・攻撃力やアーマークラスの指定方法について

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#57]
アーマークラスの指定方法について確認いたします。

NPCからの購入品や、ゾンビドラゴンの柱の効果による劣化について。
`錆`や`ヒビ`等を指定するのでしょうか
それとも`劣化`と統一して指定するのでしょうか

おそらくヒビなどと記載したのは私だと思いますので、
私の仕様の確認漏れだと思いますが、念のため確認いたします。

スキーマで設定いたしますので、もしよろしければご回答いただければと思います。

また、併せて指定可能なものは`劣化`（劣化と統一する場合）、`NG`、`HG`のみでよろしいでしょうか？
`MG`が登録されているアイテムがいくつかあるみたいです。

---
追記
別件で調査していたところ、`NG(War)`という表記が見つかりました。War Ageでの性能変化時のステータスを表記するための物と思われます。これらは許容する方向かどうかもご指示下さい。
また、同時に`HG(War)`等も状況によっては必要になると思われます。`(War)`もこのままの表記でいいか確認いただければ…

確認内容まとめ
- `劣化`か、劣化名を指定するかの確認
- `MG`を許容するか
- `(War)`絡みを許容するか、文字列はこのままでいいか

**Comment by coop-mojo** [comment]
> - 劣化か、劣化名を指定するかの確認

劣化品は全て `劣化` で統一しましょう！

> - MGを許容するか

`MG` も含めましょう (おそらく `MG` しか入手可能でないアイテムがあるため)

> - (War)絡みを許容するか、文字列はこのままでいいか

文字列も含めて現行のままでいきましょう！
(利用方法によっては別の方式のほうがいいかもしれませんが、それはアプリが出てから考えます！)

> 同時にHG(War)等も状況によっては必要になると思われます。

HG が作れるアイテムで、War Age で性能が代わるものってありましたっけ？
把握している範囲では購入品などしかなかった気がします。

**Comment by Helestia** [comment]
`劣化`に統一は了解いたしました。

> `MG`も含めましょう (おそらく MG しか入手可能でないアイテムがあるため)

思いつきませんが了解いたしました。
ちなみに`MG`が指定された場合は`NG`を登録不可にするなどの細工は必要ですか？

Warで性能変化する生産品ですが、特殊条件`WA`付与アイテム（プレート装備やトール装備等）を想定していました。

Warが正規性能でほかの時代では性能低下するアイテムは確かに生産装備は存在しないかと思いますが、特殊条件WAについてはWarの性能が必要なことも想定するべきなのかなと。

とりあえずまずは`劣化`に統一するPRを出させていただきます。
よろしくお願いいたします。

**Comment by coop-mojo** [comment]
> 思いつきませんが了解いたしました。

イベントなどで入手可能な GM の銘入りなどはそれに当たるかと思います。
あと [ウェディングリング](https://github.com/coop-mojo/moecoop-data/blob/49083994faf015a37dee6c76ea7af36a89cf6ac9/resource/%E9%98%B2%E5%85%B7/%E8%AA%B2%E9%87%91%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0/%E3%82%B0%E3%83%A9%E8%A3%85%E5%82%992.json#L218) とか(おそらく相方の銘を入れるイベントがあった？)。

> 特殊条件WAについてはWarの性能が必要なことも想定するべきなのかなと。

確かにそうですね。War Age での HG 性能とかを入力した覚えがなかったので、てっきり無いものかと思ってました…
