### ISSUE TITLE
装飾品　背中装備部位名の表記ゆれについて

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#58]
装備箇所の設定について、装飾品の背中部位について確認いたします。

現状では`背中(装)`と`背(装)`が存在しており、どちらかに合わせたいと考えております。
他の部位に表記揺れは今のところありませんでした。

漢字1文字ですべての部位が登録できるのであれば`背`のほうが好ましいとは思いますが、どうしても防具部位`パンツ`があるため、その方向で統一は難しそうです。

どちらにすべきでしょうか？

**Comment by coop-mojo** [comment]
ゲーム中の表記の `背中(装)` に統一しましょう！

**Comment by Helestia** [comment]
`背中(装)`に統一　了解いたしました。

作業を始めさせていただきます。
