### ISSUE TITLE
棍棒の表記について

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#70]
スキルの棍棒についてですが、ゲーム内では`こんぼう`とひらがなで表記されています。
それを参考にこれまでスキーマを作成しておりましたが、武器フォルダ内の必要スキルはすべて漢字で`棍棒`と記載されています。

ファイル名についてはスキル名ではなく武器カテゴリですので、修正する必要はないかなと私も思いますが
要求スキルについては`こんぼう`に修正したいのですが、よろしいでしょうか？

**Comment by coop-mojo** [comment]
はい！お願いします！

**Comment by Helestia** [comment]
許可していただいてありがとうございます。
それでは作業させていただきます。
