### ISSUE TITLE
レシピ格納jsonへ最大作成個数フィールドの新設について

### ISSUE THREAD

**Issue by Helestia** [coop-mojo/moecoop-data#86]
## 概要
[レシピディレクトリ](https://github.com/coop-mojo/moecoop-data/tree/master/resource/%E3%83%AC%E3%82%B7%E3%83%94)内のjsonについて、`同時作成上限セット数`等のフィールドの新設を提案します。

## 問題点
現在該当項目は備考項目に記載されています。
現状はレイアウトが均一となっていますが、下記問題が発生する恐れがあります。
 - 記載方法が崩れる可能性がある
   - コロンの半角・全角
   - 数字の半角・全角
   - コロンと数字の間にスペースが抜ける
   - 単位を「個」と指定してしまう　等
 - データを利用するためにはテキスト解析が必要。

## 解決方法
同時作成可能個数を管理するフィールドを新設し、半角入力を強制することで、上記問題の解決を図る。
JSON Schemaの支援があるため、表記の均一化が図れる。

``` JSON
    {
        "名前": "染色液",
        "材料": {
            "空瓶": 1,
            "ドロドロした液体": 1,
            "花びら": 2
        },
        "生成物": {
            "染色液": 1
        },
        "テクニック": [
            "薬調合"
        ],
        "スキル": {
            "薬調合": 23.0
        },
        "同時作成上限セット数" : 2,
        "レシピが必要": false,
        "ギャンブル型": false,
        "ペナルティ型": false
    },
```
新設フィールドは任意項目とすることで無関係なデータの修正を避けることができる。

## 考慮事項
 - フィールド名が一般的でないため、一般的な表現をつけたい…名づけ難しい…
 - `同時作成上限`で検索したところ、97件見つかりました。

以上、よろしくお願いいたします。

**Comment by coop-mojo** [comment]
備考からフィールドに移動させるのは大賛成です！
ゲーム中だと `常に最大生産` の表記くらいしかないので悩ましいですね… > フィールド名
備考欄で多く使われてそうな `同時作成上限` にするのはどうでしょう？

**Comment by Helestia** [comment]
作成セット数を表記するため、例えば`ドブロク`なんかは(1コンバイン2つ作成、5セットまで同時作成可能)5を指定するか、10を指定するか混乱するかなとか考えていました。

`同時作成上限`でよろしいのでしたらその旨をお返事ください。作業を開始します。
他に適切な表現があればうれしいです

**Comment by coop-mojo** [comment]
備考欄で `同時作成上限` としたときの意図は、同時にコンバインできる数でした。
そういう意味では、`同時作成上限` はあんまり良くないかもしれませんね… (対応するスキル値100でも変化するため、
どちらにしろ混乱しそうですが)

`同時作成回数上限` の方が誤解が少ないかもしれないですね。いかがでしょう？

**Comment by Helestia** [comment]
こういうところでセンスのある提案ができない自分が歯がゆいです…

`同時作成回数上限`で作業を開始します。
もっといい表現があったら最悪フォルダ内を置換すれば一発なので、思いついたら別途提案するという形で！

日付が変わるくらいまでには終わる予定です。
